# Generated by Django 4.1 on 2022-08-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
