# Generated by Django 4.1 on 2022-08-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
