# Generated by Django 5.0.2 on 2024-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_address_customer_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
